tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace

      # Install AWS CLI
      curl 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip' -o 'awscliv2.zip'
      unzip awscliv2.zip
      sudo ./aws/install
      aws --version  # Verify the AWS CLI installation
 

  - name: psql
    init: |
      cd /workspace
      # Install PostgreSQL client (psql)
      sudo apt-get update
      sudo apt-get install -y postgresql-client
      psql --version  # Verify the psql installation
    command:
      export GITPOD_IP=$(curl ifconfig.me)
      source "$THEIA_WORKSPACE_ROOT/backend-flask/bin/rds-update-sg-rule" 
      
      
      cd $THEIA_WORKSPACE_ROOT


  - name: react-js
    command:
      cd frontend-react-js && npm i

vscode:
  extensions:
    - 42Crunch.vscode-openapi

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public
